# Generated by Django 3.2.25 on 2024-10-29 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor', '0002_doctorlist_hospitalname'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='doctorlist',
            unique_together={('doctorName', 'hospitalName')},
        ),
    ]
